monolog:
    handlers:
        main:
            type:         fingers_crossed
            # 500 errors are logged at the critical level
            #action_level: critical
            # to also log 400 level errors (but not 404's):
            action_level: error
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
            handler:      grouped
        grouped:
            type:    group
            members: [streamed, deduplicated]
        streamed:
            type:  stream
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        deduplicated:
            type:    deduplication
            handler: swift
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        swift:
            type:       swift_mailer
            from_email: 'jf@marche.be'
            to_email:   'webmaster@marche.be'
            subject:    'Sepulture Error Occurred! %%message%%'
            level:      debug
            formatter:  monolog.formatter.html
            content_type: text/html